# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da7b7ea766b87994dd2b68ae00cb0ebb75772a024df498ace1bf4067f6f91e70aab2ef3d66f87fb8bfb805ab1deee978e07f2326007fa5a29f80c2d6d549b6be

test:
  secret_key_base: da7b7ea766b87994dd2b68ae00cb0ebb75772a024df498ace1bf4067f6f91e70aab2ef3d66f87fb8bfb805ab1deee978e07f2326007fa5a29f80c2d6d549b6be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
